
name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1

    - name: 'Setup Java'
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: 'gradle: Build (skipping tests for now) push and release to heroku'
      run: ./gradlew herokuDeploy -x test
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Deployment Logs
      run: heroku logs --app nokri-nokri --num 500
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}