
name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1

    - name: Login to Heroku Container registry
      run: heroku container:login
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Build
      run: ./gradlew build

    - name: Build and Push
      run: heroku container:push web --app nokri-nokri
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Release
      run: heroku container:release web --app nokri-nokri
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Deployment Logs
      run: heroku logs --app nokri-nokri --num 500
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}