
name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1

    - name: Login to Heroku Container registry
      run: heroku container:login
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: 'Gradle Cache'
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ${{ github.workspace }}/backend/build-cache
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle-

    - name: 'Build (skipping tests for now)'
      run: ./gradlew build -x test

    - name: Build and Push
      run: heroku container:push web --app nokri-nokri
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Release
      run: heroku container:release web --app nokri-nokri
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Deployment Logs
      run: heroku logs --app nokri-nokri --num 500
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}